### ISSUE TITLE
需要优化更新数据速度

### ISSUE THREAD

**Issue by Billdex** [Billdex/bcjh-bot#11]
随着内容的增加，每次更新数据花费的时间越来越久，现在执行一次全量更新需要10-20分钟，有必要优化一下更新数据性能了

初步评估后，当前可优化的耗时较长项目的有如下：
- 后厨合成菜谱数据，耗时约7s 。图鉴网的数据没有对后厨菜进行直接的数据关联，数据处理主要耗时在查库和写库方面，可以优化读写过程，减少对数据库的操作。
- 厨师 (4-6min) 菜谱 (5-8min) 厨具 (2-3min) 。观察运行时性能监控(宿主机实例为2c4g)，可以发现在图片更新过程中, cpu与内存 的资源使用率仍然是较低的状态(cpu 低于20%，内存约250M), 可以适当调整更新过程的执行顺序，充分利用并发性能，提高资源利用率与图片绘制速度。同时在该过程中存在多个查询数据库的操作，可以将该部分数据提前缓存，减少数据库 IO

**Comment by 2015WUJI01** [comment]
好！

**Comment by Billdex** [comment]
后厨数据更新流程已优化，合并到菜谱数据的更新流程里了，具体实现可以查看 [此次提交](https://github.com/Billdex/bcjh-bot/commit/606d3c91ec40818d3aaa6cf432464e4478999bdc)

**Comment by Billdex** [comment]
#27 已调整绘制流程，图片更新过程改为并行执行，在 2c4g 服务器上去除图片下载时间后累计更新时间可压缩到约4m30s，绘图过程中cpu占用约50%，内存占用约650MB，在可接受的范围。更新过程中的数据查询已粗略实现 dao 层，后续接入缓存之后可进一步减少时间
