### ISSUE TITLE
goreleaser 添加一个安卓版本

### ISSUE THREAD

**Issue by 2015WUJI01** [Billdex/bcjh-bot#19]
在手机 termux 上部署 linux 会报 `lookup xxx on [::1]:37606-＞[::1]:53: read: connection refused` 这样的错。

查了很多资料发现是安卓手机内核不支持的原因，所以编译的时候用 `goos=android` 单独编译安卓版本即可。

参考资料：
- https://blog.csdn.net/halozhy/article/details/121217726
- https://stackoverflow.com/questions/38959067/dns-lookup-issue-when-running-my-go-app-in-termux
- [https://github.com/termux/termux-app/issues/869](https://github.com/termux/termux-app/issues/869)

**Comment by Billdex** [comment]
已合并
