### ISSUE TITLE
删除了图片中的稀有度图片之后，无法生成随机个人图鉴

### ISSUE THREAD

**Issue by Watermelon233** [Billdex/bcjh-bot#43]
目录resource/image/chef
目前生成随机个人图鉴需要以下图片
rarity_1.png
rarity_2.png
rarity_3.png
rarity_4.png
rarity_5.png

**Comment by Billdex** [comment]
感谢反馈，你可以临时从 resource/image/common 中复制稀有度图片素材至 resource/image/chef
我会在下一个版本中修复该问题，重新指向素材引用
