### ISSUE TITLE
如何部署嗷呜

### ISSUE THREAD

**Issue by Watermelon233** [Billdex/bcjh-bot#9]
各位大佬 有时间的时候可以写一下如何部署嗷呜吗。一个嗷呜倒下了千万个嗷呜支棱起来了 :D

**Comment by Billdex** [comment]
> 各位大佬 有时间的时候可以写一下如何部署嗷呜吗。一个嗷呜倒下了千万个嗷呜支棱起来了 :D

好的，最近在计划重构项目，到时候配置会跟现在的有些不一样，等重构完成之后就把部署说明补上

**Comment by Watermelon233** [comment]
好的谢谢 辛苦各位大佬

**Comment by Billdex** [comment]
部署文档写好了，鸽了一年了 hhh
http://bcjhbot.billdex.cn/#/install/install

**Comment by Watermelon233** [comment]
感谢大佬 👍
